[platformio]
src_dir = src
default_envs = esp

[env]
platform = espressif32@54.3.20
framework = arduino
board = lolin_s2_mini
monitor_speed = 115200

lib_extra_dirs = ../common

build_flags =
  -Isrc
  -I../common/cfg/
  -I../common/src/

build_src_filter =
  +<*>
  -<.git/>
  -<.svn/>

[env:esp]
upload_protocol = espota
upload_port = tank_greenhouse.local
#upload_port = COM4
