[platformio]
src_dir = src
default_envs = esp

[env]
platform = espressif32@6.10.0
framework = arduino
board = esp32-c3-devkitc-02
monitor_speed = 115200

lib_extra_dirs = ../common

build_flags =
  -Isrc
  -I../common/cfg/
  -I../common/src/

build_src_filter =
  +<*>
  -<.git/>
  -<.svn/>

[env:esp]
build_flags =
  ${env.build_flags}
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_USB_MODE=1

#upload_protocol = espota
#upload_port = irrigator.local
upload_port = COM9
upload_speed = 921600