[platformio]
src_dir = src
default_envs = esp

[env]
platform = espressif8266
framework = arduino
board = d1_mini
monitor_speed = 115200

lib_deps =
  luisllamasbinaburo/MeanFilterLib@^1.0.0
  luisllamasbinaburo/MedianFilterLib@^1.0.1
  wizard97/RingBufCPP@^1.3
  paulstoffregen/Time@^1.6.1
  arduino-libraries/NTPClient@^3.2.1

lib_extra_dirs = ../common

build_flags =
  -Isrc
  -I../common/cfg/
  -I../common/src/

#board_build.filesystem = littlefs

build_src_filter =
  +<*>
  -<.git/>
  -<.svn/>

[env:esp]
build_flags =
  ${env.build_flags}

upload_protocol = espota
upload_port = tank.local
#upload_port = COM5